version: "3.6"

services:

  backend:
    container_name: project_name
    build: ./project_name
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    env_file:
      - project_name/.env
    ports:
      - "8000:8000"
    depends_on:
      - mariadb
    volumes:
      - ./project_name:/project
    networks:
      - project_name_net

  mariadb:
    container_name: project_name_mariadb
    image: mariadb:10.2.8
    # image: arm64v8/mariadb:latest
    restart: always
    env_file:
      - project_name/.env
    ports:
      - "3306:3306"
    volumes:
      - project_name:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    networks:
      - project_name_net

  redis:
    container_name: project_name_redis
    image: redis:alpine
    networks:
      - project_name_net

volumes:
  project_name:


networks:
  project_name_net:
    driver: bridge
