version: "3.6"
services:

  backend:
    container_name: project_name_backend
    build: ./project_name
    command: python3 manage.py runserver 0.0.0.0:8000
    env_file:
      - project_name/.env
    volumes:
      - ./project_name:/project
    depends_on:
      - mariadb
    networks:
      - project_name_net
    ports:
      - "8000:8000"
    restart: always

  mariadb:
    container_name: project_name_mariadb
    image: mariadb:10.2.8
    # image: arm64v8/mariadb:latest
    hostname: project_name_mariadb
    env_file:
      - project_name/.env
    networks:
      - project_name_net
    volumes:
      - project_name:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
    restart: always

volumes:
  project_name:


networks:
  project_name_net:
    driver: bridge
